// Generated by SchemaGen 12.06.2023 07:00:32

using System;
using WisejLib;

namespace DemoApp.Schema
{
	[Tablename("Settings")]
	public class Settings : DbEntity
	{
		public int UserId { get => GetProperty<int>(); set => SetProperty(value); }
		public string SettingsName { get => GetProperty<string>(); set => SetProperty(value); }
		public string SettingsData { get => GetProperty<string>(); set => SetProperty(value); }
	}
}
